name: codal-buildpr

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nedseb/arm-gcc-none-eabi:latest
      options: --user 1001 --security-opt no-new-privileges
    steps:
      - name: checkout codal
        uses: actions/checkout@v2
        with:
          repository: letssteam/codal-letssteam
          path: codal

      - name: checkout codal-core
        uses: actions/checkout@v2
        with:
          repository: letssteam/codal-core
          path: codal/libraries/codal-core

      - name: checkout codal-stm32
        uses: actions/checkout@v2
        with:
          repository: letssteam/codal-stm32
          path: codal/libraries/codal-stm32

      - name: checkout PR
        uses: actions/checkout@v2
        with:
          path: codal/libraries/codal-stm32-NUCLEO_F4x1RE
      - name: create codal.json
        run: |
          echo \
            '{
              "target": {
              "name": "codal-stm32-NUCLEO_F4x1RE", 
              "url": "https://github.com/letssteam/codal-stm32-NUCLEO_F4x1RE",
              "branch": "main",
              "type": "git",
              "dev": true
            }}' > codal/codal.json
      
      - name: build PR
        run: |
          cd codal
          ./build.py -c
